SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE BILL_PRODUCT;
TRUNCATE DISCOUNT_MODEL;
TRUNCATE PRODUCT;
TRUNCATE BILL;
TRUNCATE USER;
TRUNCATE TYPE;
TRUNCATE DISCOUNT;
TRUNCATE MODEL;
SET FOREIGN_KEY_CHECKS = 1;

